"""
Safe Virus Simulation — educational only.

- Entirely in-memory simulation.
- Models hosts on a network graph, infection spread, detection, and mitigation.
- DOES NOT perform any real file/network operations, no persistence, no shell/OS calls.
- Suitable for classroom/demonstration use.

How to use:
- Run this in a Python 3.8+ environment.
- Optional: tweak parameters in the `if __name__ == "__main__":` block.
"""

import random
import math
from collections import deque, defaultdict
import matplotlib.pyplot as plt
import networkx as nx

random.seed(42)


class Host:
    """Represents a simulated host in the network."""
    def __init__(self, id, os_type="linux", baseline_cpu=5.0, patched=False):
        self.id = id
        self.os_type = os_type
        self.baseline_cpu = baseline_cpu  # baseline CPU usage percent
        self.cpu = baseline_cpu
        self.infected = False
        self.infection_age = 0
        self.quarantined = False
        self.patched = patched
        # simulated logs/events (kept small and in-memory)
        self.logs = deque(maxlen=500)

    def step_idle(self):
        """Advance one time-step for benign behavior (small random fluctuation)."""
        # small gaussian noise around baseline
        self.cpu = max(0.0, random.gauss(self.baseline_cpu, self.baseline_cpu * 0.1))

    def apply_infection(self, behavior_profile):
        """Mark infected and initialize infection effects."""
        self.infected = True
        self.infection_age = 0
        self.behavior_profile = behavior_profile
        self.logs.append(f"Infected with profile {behavior_profile.name}")

    def simulate_malware_activity(self):
        """Simulate malware-driven anomalies (CPU spikes, scans) returning events list."""
        events = []
        if not self.infected or self.quarantined:
            return events

        # Increase infection_age
        self.infection_age += 1

        # CPU spike (simulated)
        cpu_spike = self.behavior_profile.cpu_load_func(self.infection_age)
        self.cpu = max(self.cpu, cpu_spike)

        # Possibly log a suspicious activity event (scan attempts, credential use)
        if self.behavior_profile.scan_chance(self.infection_age) > random.random():
            events.append({"type": "network_scan", "host": self.id, "age": self.infection_age})
            self.logs.append("Performed network scan")

        if self.behavior_profile.data_exfiltrate_chance(self.infection_age) > random.random():
            events.append({"type": "data_exfil", "host": self.id, "age": self.infection_age})
            self.logs.append("Attempted data exfiltration (simulated)")

        return events

    def quarantine(self):
        self.quarantined = True
        self.logs.append("Host quarantined by defender")

    def patch(self):
        self.patched = True
        self.logs.append("Host patched by defender")
        # optionally heal infection on patch
        if self.infected:
            self.infected = False
            self.infection_age = 0
            self.logs.append("Infection removed by patch (simulated)")

    def __repr__(self):
        return f"Host({self.id}, infected={self.infected}, cpu={self.cpu:.1f})"


class BehaviorProfile:
    """Describes the simulated 'malware' behavior over time."""
    def __init__(self, name, peak_cpu=60.0, stealthy=False):
        self.name = name
        self.peak_cpu = peak_cpu
        self.stealthy = stealthy

    def cpu_load_func(self, age):
        """Returns temporary CPU load generated by malware at infection age."""
        # A simple curve: small at first, then ramp, maybe periodic bursts
        base = self.peak_cpu * (1 - math.exp(-0.2 * age))
        burst = 0
        # stealthy malware has rarer bursts; noisy malware bursts frequently
        burst_chance = 0.05 if self.stealthy else 0.2
        if random.random() < burst_chance:
            burst = random.uniform(0.1 * self.peak_cpu, 0.5 * self.peak_cpu)
        return base + burst

    def scan_chance(self, age):
        """Probability of performing a network scan at this step."""
        return 0.05 + 0.01 * (age // 5)  # slowly increasing

    def data_exfiltrate_chance(self, age):
        """Probability of attempting data exfiltration."""
        return 0.02 if self.stealthy else 0.08


class Defender:
    """Represents a defender system: signature-based and anomaly-based detection."""
    def __init__(self, signature_db=None, anomaly_threshold=25.0):
        # signature_db: set of known behavior profile names (strings) to detect
        self.signature_db = set(signature_db or [])
        self.anomaly_threshold = anomaly_threshold  # CPU percent above baseline indicates anomaly
        self.alerts = []

    def analyze_host_events(self, host, events):
        """Analyze events produced by a host and raise alerts."""
        # 1) Signature detection
        if host.infected and getattr(host, "behavior_profile", None):
            if host.behavior_profile.name in self.signature_db:
                alert = {"host": host.id, "type": "signature", "profile": host.behavior_profile.name}
                self.alerts.append(alert)
                return alert

        # 2) Event-based heuristics (network scan, exfil)
        for e in events:
            if e["type"] == "network_scan":
                alert = {"host": host.id, "type": "scan_detected", "age": e["age"]}
                self.alerts.append(alert)
                return alert
            if e["type"] == "data_exfil":
                alert = {"host": host.id, "type": "exfiltration_detected", "age": e["age"]}
                self.alerts.append(alert)
                return alert

        # 3) Anomaly detection using CPU delta from baseline
        cpu_delta = host.cpu - host.baseline_cpu
        if cpu_delta > self.anomaly_threshold:
            alert = {"host": host.id, "type": "anomaly", "cpu_delta": cpu_delta}
            self.alerts.append(alert)
            return alert

        return None

    def respond_to_alert(self, alert, network):
        """Perform defender action: quarantine or patch based on alert type."""
        if not alert:
            return None
        host = network.nodes[alert["host"]]["obj"]
        if alert["type"] in ("signature", "exfiltration_detected", "scan_detected"):
            host.quarantine()
            return ("quarantine", host.id)
        if alert["type"] == "anomaly":
            # less certain: try patching some percentage of anomalies
            if random.random() < 0.6:
                host.patch()
                return ("patch", host.id)
            else:
                host.quarantine()
                return ("quarantine", host.id)
        return None


class NetworkSimulator:
    """Simulates time steps on a graph of hosts."""
    def __init__(self, graph: nx.Graph, defender: Defender, behavior_profiles):
        """
        graph: networkx Graph where each node has Host object under 'obj'
        defender: Defender instance
        behavior_profiles: dict name -> BehaviorProfile
        """
        self.graph = graph
        self.defender = defender
        self.behavior_profiles = behavior_profiles
        self.time = 0
        self.infection_history = []

    def step(self):
        """Advance simulation by one timestep."""
        self.time += 1
        infections_this_step = []
        # 1) Simulate host idle behavior
        for nid, data in self.graph.nodes(data=True):
            host: Host = data["obj"]
            if not host.infected:
                host.step_idle()

        # 2) For infected hosts, simulate malware activity and attempt to infect neighbors
        for nid, data in self.graph.nodes(data=True):
            host: Host = data["obj"]
            events = []
            if host.infected and not host.quarantined:
                events = host.simulate_malware_activity()

                # Attempt to infect each neighbor based on infection probability
                neighbors = list(self.graph.neighbors(nid))
                for nb in neighbors:
                    nb_host: Host = self.graph.nodes[nb]["obj"]
                    if nb_host.patched or nb_host.quarantined or nb_host.infected:
                        continue
                    # infection probability depends on behavior profile stealthiness and defender coverage
                    profile = host.behavior_profile
                    base_prob = 0.15 if not profile.stealthy else 0.06
                    # reduce success if defender has signatures for this profile
                    if profile.name in self.defender.signature_db:
                        base_prob *= 0.1
                    # random chance
                    if random.random() < base_prob:
                        # Infect neighbor
                        nb_host.apply_infection(profile)
                        infections_this_step.append(nb_host.id)

            # 3) defender analyzes host and events
            alert = self.defender.analyze_host_events(host, events)
            if alert:
                action = self.defender.respond_to_alert(alert, self.graph)
                # optional: propagate defender actions (patch neighbors)
                if action and action[0] == "quarantine":
                    # defenders might proactively patch some neighbors
                    for nb in self.graph.neighbors(nid):
                        if random.random() < 0.05:
                            self.graph.nodes[nb]["obj"].patch()

        # record statistics
        infected_count = sum(1 for _, d in self.graph.nodes(data=True) if d["obj"].infected)
        quarantined_count = sum(1 for _, d in self.graph.nodes(data=True) if d["obj"].quarantined)
        self.infection_history.append({"time": self.time, "infected": infected_count, "quarantined": quarantined_count})
        return infections_this_step

    def run(self, steps=50, verbose=False):
        for _ in range(steps):
            new = self.step()
            if verbose:
                print(f"t={self.time}: new infections={new} total_infected={self.infection_history[-1]['infected']}")


def build_random_network(n_hosts=50, degree=3):
    """Create a random networkx graph with Host objects assigned to nodes."""
    # use Watts-Strogatz small-world model to simulate realistic local + long-range connections
    G = nx.watts_strogatz_graph(n_hosts, k=degree, p=0.1, seed=random.randint(0, 10000))
    for n in G.nodes():
        # random baseline cpu 1-10%
        host = Host(id=n, baseline_cpu=random.uniform(1.0, 10.0))
        G.nodes[n]["obj"] = host
    return G


def plot_infection_history(history):
    times = [h["time"] for h in history]
    infected = [h["infected"] for h in history]
    quarantined = [h["quarantined"] for h in history]

    plt.figure(figsize=(8, 4))
    plt.plot(times, infected)
    plt.plot(times, quarantined)
    plt.xlabel("Time step")
    plt.ylabel("Count")
    plt.title("Infected vs Quarantined over time")
    plt.legend(["Infected", "Quarantined"])
    plt.tight_layout()
    plt.show()


def example_run():
    # Create behavior profiles
    stealthy = BehaviorProfile(name="stealthy_keylogger", peak_cpu=30.0, stealthy=True)
    noisy = BehaviorProfile(name="noisy_ransomish", peak_cpu=80.0, stealthy=False)
    profiles = {stealthy.name: stealthy, noisy.name: noisy}

    # Defender knows signature for noisier profile but not for stealthy one
    defender = Defender(signature_db=[noisy.name], anomaly_threshold=20.0)

    # Build network
    G = build_random_network(n_hosts=80, degree=4)

    sim = NetworkSimulator(graph=G, defender=defender, behavior_profiles=profiles)

    # Infect a small set of seed hosts
    seed_hosts = random.sample(list(G.nodes()), k=3)
    for s in seed_hosts:
        profile = random.choice([stealthy, noisy])
        G.nodes[s]["obj"].apply_infection(profile)

    # Run simulation
    sim.run(steps=60, verbose=False)

    # Outputs
    print("Final stats:")
    final = sim.infection_history[-1]
    print(f"Time {final['time']}: infected={final['infected']}, quarantined={final['quarantined']}")
    plot_infection_history(sim.infection_history)

    # Example: show logs of some hosts
    print("\nSample host logs (3 hosts):")
    sample_ids = random.sample(list(G.nodes()), 3)
    for sid in sample_ids:
        h = G.nodes[sid]["obj"]
        print(f"Host {sid}: infected={h.infected}, quarantined={h.quarantined}, logs={list(h.logs)[-5:]}")

if __name__ == "__main__":
    example_run()
